In [1]:
import pandas as pd

pd.read_csv("BS.csv")

FileNotFoundError: File b'BS.csv' does not exist

In [2]:
pwd

'C:\\Users\\lijia.DESKTOP-GBRD99U'

In [4]:
cd PycharmProjects\BF3210

C:\Users\lijia.DESKTOP-GBRD99U\PycharmProjects\BF3210

In [5]:
pwd

'C:\\Users\\lijia.DESKTOP-GBRD99U\\PycharmProjects\\BF3210'

In [1]:
import pandas as pd

pd.read_csv("BS.csv")

FileNotFoundError: File b'BS.csv' does not exist

In [2]:
pwd

'C:\\Users\\lijia.DESKTOP-GBRD99U'

In [3]:
cd \PycharmProjects\BF3210

[WinError 3] The system cannot find the path specified: '\\PycharmProjects\\BF3210'
C:\Users\lijia.DESKTOP-GBRD99U

In [4]:
cd PycharmProjects\BF3210

C:\Users\lijia.DESKTOP-GBRD99U\PycharmProjects\BF3210

In [5]:
import pandas as pd

pd.read_csv("BS.csv")

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Year</th>
      <th>2013</th>
      <th>2014</th>
      <th>2015</th>
      <th>2016</th>
      <th>2017</th>
      <th>2018</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Cash And Equivalents</td>
      <td>5,459.10</td>
      <td>5,616.20</td>
      <td>1,734.60</td>
      <td>1,874.10</td>
      <td>2,106.10</td>
      <td>1,971.80</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Short Term Investments</td>
      <td>363.4</td>
      <td>261.1</td>
      <td>125.6</td>
      <td>126.9</td>
      <td>55</td>
      <td>136.6</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Trading Asset Securities</td>
      <td>81.6</td>
      <td>110.3</td>
      <td>99.5</td>
      <td>147.1</td>
      <td>147.7</td>
      <td>-</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Total Cash &amp; ST Investments</td>
      <td>5,904.20</td>
      <td>5,987.60</td>
      <td>1,959.70</td>
      <td>2,148.10</td>
      <td>2,308.90</td>
      <td>2,108.40</td>
    </tr>
    <tr>
      <th>4</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Accounts Receivable</td>
      <td>1,306.60</td>
      <td>1,566.20</td>
      <td>2,149.10</td>
      <td>2,613.30</td>
      <td>2,224.60</td>
      <td>6,206.70</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Other Receivables</td>
      <td>373.8</td>
      <td>524.8</td>
      <td>607.4</td>
      <td>556.6</td>
      <td>634.3</td>
      <td>-</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Notes Receivable</td>
      <td>853.3</td>
      <td>504.9</td>
      <td>399</td>
      <td>373.4</td>
      <td>291.7</td>
      <td>-</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Total Receivables</td>
      <td>2,533.60</td>
      <td>2,596.00</td>
      <td>3,155.60</td>
      <td>3,543.30</td>
      <td>3,150.70</td>
      <td>6,206.70</td>
    </tr>
    <tr>
      <th>9</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Inventory</td>
      <td>8,994.70</td>
      <td>10,681.10</td>
      <td>10,762.60</td>
      <td>10,025.80</td>
      <td>8,782.30</td>
      <td>5,514.00</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Prepaid Exp.</td>
      <td>63.6</td>
      <td>60.9</td>
      <td>61.8</td>
      <td>88.3</td>
      <td>118.6</td>
      <td>-</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Restricted Cash</td>
      <td>105.6</td>
      <td>119.8</td>
      <td>158.2</td>
      <td>212.9</td>
      <td>167.7</td>
      <td>9.6</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Other Current Assets</td>
      <td>355.7</td>
      <td>1,741.90</td>
      <td>411.5</td>
      <td>274.6</td>
      <td>424.3</td>
      <td>46</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Total Current Assets</td>
      <td>17,957.40</td>
      <td>21,187.40</td>
      <td>16,509.50</td>
      <td>16,293.00</td>
      <td>14,952.40</td>
      <td>13,884.70</td>
    </tr>
    <tr>
      <th>15</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Gross Property, Plant &amp; Equipment</td>
      <td>5,891.70</td>
      <td>4,750.80</td>
      <td>5,122.10</td>
      <td>5,116.00</td>
      <td>4,801.20</td>
      <td>-</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Accumulated Depreciation</td>
      <td>-2,093.40</td>
      <td>-2,077.80</td>
      <td>-2,276.60</td>
      <td>-2,470.50</td>
      <td>-2,368.20</td>
      <td>-</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Net Property, Plant &amp; Equipment</td>
      <td>3,798.30</td>
      <td>2,673.00</td>
      <td>2,845.50</td>
      <td>2,645.50</td>
      <td>2,433.00</td>
      <td>2,372.60</td>
    </tr>
    <tr>
      <th>19</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Long-term Investments</td>
      <td>5,746.90</td>
      <td>5,346.80</td>
      <td>5,804.80</td>
      <td>5,790.30</td>
      <td>6,359.90</td>
      <td>6,704.40</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Goodwill</td>
      <td>59.3</td>
      <td>60.7</td>
      <td>59.3</td>
      <td>59.3</td>
      <td>59.3</td>
      <td>-</td>
    </tr>
    <tr>
      <th>22</th>
      <td>Other Intangibles</td>
      <td>19.1</td>
      <td>34.6</td>
      <td>33.4</td>
      <td>60.6</td>
      <td>54.3</td>
      <td>129</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Loans Receivable Long-Term</td>
      <td>278.9</td>
      <td>294.5</td>
      <td>-</td>
      <td>285.2</td>
      <td>279</td>
      <td>-</td>
    </tr>
    <tr>
      <th>24</th>
      <td>Deferred Charges, LT</td>
      <td>7.9</td>
      <td>6.4</td>
      <td>7.1</td>
      <td>20.8</td>
      <td>19.1</td>
      <td>-</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Other Long-Term Assets</td>
      <td>2,187.90</td>
      <td>1,987.50</td>
      <td>3,661.00</td>
      <td>4,079.60</td>
      <td>3,955.90</td>
      <td>3,515.70</td>
    </tr>
    <tr>
      <th>26</th>
      <td>Total Assets</td>
      <td>30,055.60</td>
      <td>31,590.90</td>
      <td>28,920.60</td>
      <td>29,234.20</td>
      <td>28,112.80</td>
      <td>26,606.30</td>
    </tr>
    <tr>
      <th>27</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Accounts Payable</td>
      <td>778.7</td>
      <td>848.9</td>
      <td>651.2</td>
      <td>605.9</td>
      <td>613.5</td>
      <td>-</td>
    </tr>
    <tr>
      <th>29</th>
      <td>Accrued Exp.</td>
      <td>2,153.80</td>
      <td>2,158.00</td>
      <td>2,307.50</td>
      <td>1,992.80</td>
      <td>2,443.20</td>
      <td>-</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>53</th>
      <td>Total Liabilities And Equity</td>
      <td>30,055.60</td>
      <td>31,590.90</td>
      <td>28,920.60</td>
      <td>29,234.20</td>
      <td>28,112.80</td>
      <td>26,606.30</td>
    </tr>
    <tr>
      <th>54</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>55</th>
      <td>Total Shares Out. on Filing Date</td>
      <td>1,808.00</td>
      <td>1,811.80</td>
      <td>1,811.10</td>
      <td>1,815.70</td>
      <td>1,816.10</td>
      <td>1,812.50</td>
    </tr>
    <tr>
      <th>56</th>
      <td>Total Shares Out. on Balance Sheet Date</td>
      <td>1,808.00</td>
      <td>1,811.80</td>
      <td>1,811.10</td>
      <td>1,815.70</td>
      <td>1,818.30</td>
      <td>1,812.50</td>
    </tr>
    <tr>
      <th>57</th>
      <td>Book Value/Share</td>
      <td>5.37</td>
      <td>5.73</td>
      <td>6.13</td>
      <td>6.42</td>
      <td>6.29</td>
      <td>6.22</td>
    </tr>
    <tr>
      <th>58</th>
      <td>Tangible Book Value</td>
      <td>9,622.80</td>
      <td>10,285.40</td>
      <td>11,003.00</td>
      <td>11,539.10</td>
      <td>11,319.20</td>
      <td>11,149.20</td>
    </tr>
    <tr>
      <th>59</th>
      <td>Tangible Book Value/Share</td>
      <td>5.32</td>
      <td>5.68</td>
      <td>6.08</td>
      <td>6.36</td>
      <td>6.23</td>
      <td>6.15</td>
    </tr>
    <tr>
      <th>60</th>
      <td>Total Debt</td>
      <td>7,463.10</td>
      <td>7,700.00</td>
      <td>8,557.30</td>
      <td>9,358.20</td>
      <td>8,189.40</td>
      <td>7,548.50</td>
    </tr>
    <tr>
      <th>61</th>
      <td>Net Debt</td>
      <td>1,559.00</td>
      <td>1,712.40</td>
      <td>6,597.60</td>
      <td>7,210.20</td>
      <td>5,880.50</td>
      <td>5,440.10</td>
    </tr>
    <tr>
      <th>62</th>
      <td>Debt Equivalent Oper. Leases</td>
      <td>677</td>
      <td>857.2</td>
      <td>877</td>
      <td>844.9</td>
      <td>752.7</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>63</th>
      <td>Total Minority Interest</td>
      <td>3,987.70</td>
      <td>4,346.90</td>
      <td>830.2</td>
      <td>674.7</td>
      <td>527.7</td>
      <td>308.9</td>
    </tr>
    <tr>
      <th>64</th>
      <td>Equity Method Investments</td>
      <td>5,482.20</td>
      <td>4,988.40</td>
      <td>5,409.60</td>
      <td>5,412.60</td>
      <td>5,901.30</td>
      <td>6,239.70</td>
    </tr>
    <tr>
      <th>65</th>
      <td>Inventory Method</td>
      <td>Avg Cost</td>
      <td>Avg Cost</td>
      <td>Avg Cost</td>
      <td>Avg Cost</td>
      <td>Avg Cost</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>66</th>
      <td>Raw Materials Inventory</td>
      <td>224.8</td>
      <td>173.9</td>
      <td>141.1</td>
      <td>125.7</td>
      <td>115.1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>67</th>
      <td>Work in Progress Inventory</td>
      <td>7,838.40</td>
      <td>9,200.90</td>
      <td>9,246.30</td>
      <td>8,078.60</td>
      <td>7,395.40</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>68</th>
      <td>Finished Goods Inventory</td>
      <td>965.9</td>
      <td>1,345.00</td>
      <td>1,463.70</td>
      <td>1,953.80</td>
      <td>1,362.70</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>69</th>
      <td>Land</td>
      <td>1,870.70</td>
      <td>1,838.00</td>
      <td>2,117.70</td>
      <td>2,159.20</td>
      <td>2,077.30</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>70</th>
      <td>Buildings</td>
      <td>108.8</td>
      <td>109.4</td>
      <td>113.5</td>
      <td>112.9</td>
      <td>107</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>71</th>
      <td>Machinery</td>
      <td>3,493.30</td>
      <td>2,253.50</td>
      <td>2,426.20</td>
      <td>2,592.30</td>
      <td>2,308.20</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>72</th>
      <td>Construction in Progress</td>
      <td>418.9</td>
      <td>550</td>
      <td>464.7</td>
      <td>251.6</td>
      <td>308.7</td>
      <td>-</td>
    </tr>
    <tr>
      <th>73</th>
      <td>Full Time Employees</td>
      <td>39,364</td>
      <td>38,732</td>
      <td>33,574</td>
      <td>28,879</td>
      <td>21,862</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>74</th>
      <td>Accum. Allowance for Doubtful Accts</td>
      <td>10.8</td>
      <td>6.6</td>
      <td>8.8</td>
      <td>16.9</td>
      <td>56.3</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>75</th>
      <td>Order Backlog</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>3,900.00</td>
      <td>4,300.00</td>
    </tr>
    <tr>
      <th>76</th>
      <td>Filing Date</td>
      <td>Mar-27-2015</td>
      <td>Mar-28-2016</td>
      <td>Mar-30-2017</td>
      <td>Mar-28-2018</td>
      <td>Mar-28-2018</td>
      <td>Jan-24-2019</td>
    </tr>
    <tr>
      <th>77</th>
      <td>Restatement Type</td>
      <td>RC</td>
      <td>RS</td>
      <td>RC</td>
      <td>RC</td>
      <td>O</td>
      <td>P</td>
    </tr>
    <tr>
      <th>78</th>
      <td>Calculation Type</td>
      <td>REP</td>
      <td>REP</td>
      <td>REP</td>
      <td>REP</td>
      <td>REP</td>
      <td>REP</td>
    </tr>
    <tr>
      <th>79</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>80</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>81</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>82</th>
      <td>\n               \n               \n          ...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>83 rows × 7 columns</p>
</div>

In [6]:
pip install flask

The following command must be run outside of the IPython shell:

    $ pip install flask

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/